-- MySQL Script generated by MySQL Workbench
-- 11/06/15 16:22:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventorymanagerdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventorymanagerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventorymanagerdb` DEFAULT CHARACTER SET utf8 ;
USE `inventorymanagerdb` ;

-- -----------------------------------------------------
-- Table `inventorymanagerdb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorymanagerdb`.`branch` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Address` VARCHAR(200) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Manager` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inventorymanagerdb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorymanagerdb`.`employee` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `BeginDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `Address` VARCHAR(200) NULL DEFAULT NULL,
  `UserName` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inventorymanagerdb`.`employeerole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorymanagerdb`.`employeerole` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT(11) NOT NULL,
  `RoleId` INT(11) NOT NULL,
  `CreationDate` DATE NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inventorymanagerdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorymanagerdb`.`role` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NULL DEFAULT NULL,
  `Description` VARCHAR(250) NULL DEFAULT NULL,
  `Status` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
